name: Dependency-Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Dependency-Check
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Dependency-Check
        run: |
          # Download and unzip Dependency-Check
          curl -LO https://github.com/jeremylong/DependencyCheck/releases/download/v11.1.0/dependency-check-11.1.0-release.zip
          unzip dependency-check-11.1.0-release.zip -d dependency-check

          # Set the NVD API key for faster downloads
          export NVD_API_KEY=${{ secrets.NVD_API_KEY }}

          # Ensure the directory exists and run Dependency-Check from the correct location
          cd dependency-check/dependency-check

          # Run Dependency-Check with the NVD API key
          ./bin/dependency-check.sh \
            --project "MyProject" \
            --scan . \
            --format HTML \
            --out ../dependency-check-report.html \
            --nvdApiKey $NVD_API_KEY

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: dependency-check-report.html
