name: Dependency-Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Dependency-Check
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11' 

      - name: Run Dependency-Check
        run: |
          # Ensure Dependency-Check is set up
          curl -LO https://github.com/jeremylong/DependencyCheck/releases/download/v11.1.0/dependency-check-11.1.0-release.zip
          unzip dependency-check-11.1.0-release.zip -d dependency-check
          
          # Set the path where the NVD data will be stored
          export NVD_DATA_DIR="${GITHUB_WORKSPACE}/nvd-data"

          # Run Dependency-Check with local data
          ./dependency-check/dependency-check/bin/dependency-check.sh \
            --project "MyProject" \
            --scan . \
            --format HTML \
            --out dependency-check-report.html \
            --data $NVD_DATA_DIR \
            --noupdate # Skip updates to avoid fetching the full data

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: dependency-check-report.html